### ISSUE TITLE
java NoSuchMethodError

### ISSUE THREAD

**Issue by johnjung** [mbennett-uoe/whiiif#21]
Hello,

First of all, thank you so much for sharing Whiiif. 

I'm running into some trouble getting the software up and running- hopefully I am just missing something simple. I'm using Debian 10.4 in a single docker container for testing, Solr 8.6.3, and I'm running Whiiif in development mode.

I created a Solr core called "whiiif" and I was able to successfully add a document to Solr using the index_with_plugin.py script in utils. However, when I try to run a simple search (e.g. http://localhost:5000/search/b29b1tv7xn7g?q=Chicago) Whiiif doesn't return any hits, although that string does occur in the OCR.

Flask outputs the following errors when I try that search:

[2020-10-15 20:29:38,250] INFO in views: Processing IIIF Search request for document b29b1tv7xn7g
[2020-10-15 20:29:38,251] DEBUG in views: Request original q: Chicago
[2020-10-15 20:29:38,251] DEBUG in views: Request bleached q: Chicago
[2020-10-15 20:29:38,251] DEBUG in views: Regexed manifest ID: b29b1tv7xn7g
[2020-10-15 20:29:38,251] INFO in views: Built query: http://localhost:8983/solr/whiiif/select?hl=on&hl.ocr.absoluteHighlights=true&hl.weightMatches=true&hl.ocr.limitBlock=page&hl.ocr.contextSize=1&hl.ocr.contextBlock=word&df=ocr_text&hl.ocr.fl=ocr_text&hl.snippets=4096&fq=id:b29b1tv7xn7g&q=Chicago
[2020-10-15 20:29:38,257] DEBUG in views: Solr request response code: 500
[2020-10-15 20:29:38,257] ERROR in views: Error occurred with SOLR query: <class 'json.decoder.JSONDecodeError'>
[2020-10-15 20:29:38,258] ERROR in views: Error message: Expecting value: line 1 column 1 (char 0)
172.17.0.1 - - [15/Oct/2020 20:29:38] "GET /search/b29b1tv7xn7g?q=Chicago HTTP/1.1" 200 -

Then, if I try to run the built query on it's own, I get the following error from Solr, followed by a stack trace:

HTTP ERROR 500 java.lang.NoSuchMethodError: 'org.apache.lucene.util.automaton.CharacterRunAutomaton[] de.digitalcollections.solrocr.lucene.OcrHighlighter.getAutomata(java.lang.String, org.apache.lucene.search.Query, java.util.Set)'

I dropped the solr ocr highlighter .jar file into a "server/solr/whiiif/lib" directory- but to me the error above seems to say that Solr isn't able to find the OCR highlighter at runtime. Can you tell what's going on? 

Please let me know if I can provide any additional information- and thank you so much for any help or tips you can provide!

**Comment by johnjung** [comment]
After doing a little more testing I see that I'm able to get Whiiif running if I use an older version of Solr- versions I tested from 8.0.0 to 8.3.1 work, but starting with Solr 8.4 I get the error above.

**Comment by mbennett-uoe** [comment]
Hi John,

Thanks for the bug report. Apologies for not getting back to you sooner, GitHub decided not to show or send me any notifications about this ticket!

I believe that Solr changed how the Automata objects work in 8.4 and so the older version of the plugin no longer works, hence the error you are getting with 8.4 onwards.

I know that Johannes and the team from DBMDZ have already updated the OCR highlighter plugin to handle this change, but there were also some breaking changes to their plugin API introduced at the same time that I haven't yet had time to integrate into Whiiif and test.

I'll update the README to make this clear, and hopefully I'll be able to release an updated version of Whiiif early next year that will work with the newer plugin releases and thus also Solr 8.4 onwards.

**Comment by johnjung** [comment]
It's not a problem at all- thank you again for sharing whiiif!
